apiVersion: v1
kind: Service
metadata:
  name: web
  labels:
    name: web1
    app: flask
spec:
  selector:
    name: web1 
  type: NodePort
  ports:
   - name: http
     port: 3000
     targetPort: 3000
     protocol: TCP